name:  CI/CD

on:
  pull_request:
    branches:
      - prod
  push:
    branches:
      - prod

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: build website
        run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-crediantials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: aws deploy to S3
        run: aws s3 sync ./dist/. s3://solidrewind.io
